services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: fastapi-posts-dev
    volumes:
      - ./:/app
    ports:
      - "8001:8001"
    env_file:
      - .env
